openapi: "3.0.0"
info:
  version: 1.0.0
  title: Gophkeeper auth
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - BearerAuth: [ ]
paths:
  /users/sign-up:
    post:
      operationId: signUp
      security: []
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        '201':
          description: auth created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/sign-in:
    post:
      operationId: signIn
      security: []
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignIn'
      responses:
        '200':
          description: authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/current:
    get:
      operationId: getCurrentUser
      responses:
        '200':
          description: authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SignIn:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    SignUp:
      type: object
      required:
        - login
        - password
        - firstname
        - lastname
      properties:
        login:
          type: string
        password:
          type: string
        firstname:
          type: string
        lastname:
          type: string
    User:
      type: object
      required:
        - firstname
        - lastname
      properties:
        firstname:
          type: string
        lastname:
          type: integer
    Token:
      type: object
      required:
        - token
        - expires_at
      properties:
        token:
          type: string
        expires_at:
          type: string
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT